### PR TITLE
Fix #540 - Use different timeout with global requests and log the time we waited in the report

### LINKED ISSUE #540: Use 1.25 seconds for timeout with global requests
Also log the time in the report when there are no responses indicating how long we waited.

### PR DESCRIPTION
**Pull request by gumbelmj**
1250 ms should be used as the timeout with Global Requests
200 ms should be used for DS requests

### CODE REVIEW

**Review by mmschaefer — APPROVED** [review]

**Comment by battjt** [comment]
From Eric
220 ms to BAM announcement or RTS warn of late response
600 ms time out and stop listening

**Comment by gumbelmj** [comment]
@battjt, so GLOBAL_TIMEOUT should be 600 ms?

**Comment by battjt** [comment]
I need to write it up and get sign off, that's why I left it assigned to me.  The expectation is that GLOBAL_TIMEOUT needs to be 600 ms.  We also need to add a warn when the first CM is slower than 220 ms.

**Comment by gumbelmj** [comment]
Does Eric have a source for the 600 ms?  (Other than Eric)

**Comment by battjt** [comment]
Including the timestamp in the timeout error will be the system timestamp:
-        expected += "Error: Timeout - No Response." + NL;
+        expected += "10:15:30.0000 Error: Timeout - No Response." + NL;

The packet timestamps will be from the adapter.  They will be close, but not exact.
I assume there are other instances of this inconsistency and it's "good enough"?

**Comment by gumbelmj** [comment]
@battjt, you are correct.  Given there is no response, I wanted to indicate in the report how long we waited for a response.

**Pull request merged**
